FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY Application/dotNET/ASPdotNET_Core_Web_API/ ./app/
COPY Datalayer/ ./DataLayer/

WORKDIR /src/app

RUN dotnet publish ASPdotNET_Core_Web_API.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "ASPdotNET_Core_Web_API.dll"]
