export const countryCodeToName: Record<string, string> = {
  UN: "UNKOWN - Ghost ship",
  AL: "Albania",
  AD: "Andorra",
  AT: "Austria",
  PT: "Portugal",
  BE: "Belgium",
  BY: "Belarus",
  BG: "Bulgaria",
  VA: "Vatican City",
  CY: "Cyprus",
  DE: "Germany",
  GE: "Georgia",
  MD: "Moldova",
  MT: "Malta",
  AM: "Armenia",
  DK: "Denmark",
  ES: "Spain",
  FR: "France",
  FI: "Finland",
  GB: "United Kingdom",
  GR: "Greece",
  HR: "Croatia",
  MA: "Morocco",
  HU: "Hungary",
  NL: "Netherlands",
  IT: "Italy",
  IE: "Ireland",
  IS: "Iceland",
  LI: "Liechtenstein",
  LU: "Luxembourg",
  MC: "Monaco",
  NO: "Norway",
  PL: "Poland",
  ME: "Montenegro",
  RO: "Romania",
  SE: "Sweden",
  SK: "Slovakia",
  SM: "San Marino",
  CH: "Switzerland",
  CZ: "Czech Republic",
  TR: "Turkey",
  UA: "Ukraine",
  RU: "Russia",
  MK: "North Macedonia",
  LV: "Latvia",
  EE: "Estonia",
  LT: "Lithuania",
  SI: "Slovenia",
  RS: "Serbia",
  BA: "Bosnia and Herzegovina",
  AI: "Anguilla",
  US: "United States",
  AG: "Antigua and Barbuda",
  AW: "Aruba",
  BS: "Bahamas",
  BM: "Bermuda",
  BZ: "Belize",
  BB: "Barbados",
  CA: "Canada",
  KY: "Cayman Islands",
  CR: "Costa Rica",
  CU: "Cuba",
  DM: "Dominica",
  DO: "Dominican Republic",
  GP: "Guadeloupe",
  GD: "Grenada",
  GL: "Greenland",
  GT: "Guatemala",
  HN: "Honduras",
  HT: "Haiti",
  JM: "Jamaica",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  MX: "Mexico",
  MQ: "Martinique",
  MS: "Montserrat",
  NI: "Nicaragua",
  PA: "Panama",
  PR: "Puerto Rico",
  SV: "El Salvador",
  PM: "Saint Pierre and Miquelon",
  TT: "Trinidad and Tobago",
  TC: "Turks and Caicos Islands",
  VC: "Saint Vincent and the Grenadines",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  AF: "Afghanistan",
  SA: "Saudi Arabia",
  BD: "Bangladesh",
  BH: "Bahrain",
  BT: "Bhutan",
  CN: "China",
  TW: "Taiwan",
  LK: "Sri Lanka",
  IN: "India",
  IR: "Iran",
  AZ: "Azerbaijan",
  IQ: "Iraq",
  IL: "Israel",
  JP: "Japan",
  TM: "Turkmenistan",
  KZ: "Kazakhstan",
  UZ: "Uzbekistan",
  JO: "Jordan",
  KR: "South Korea",
  PS: "Palestine",
  KP: "North Korea",
  KW: "Kuwait",
  LB: "Lebanon",
  KG: "Kyrgyzstan",
  MO: "Macao",
  MV: "Maldives",
  MN: "Mongolia",
  NP: "Nepal",
  OM: "Oman",
  PK: "Pakistan",
  QA: "Qatar",
  SY: "Syria",
  AE: "United Arab Emirates",
  TJ: "Tajikistan",
  YE: "Yemen",
  HK: "Hong Kong",
  AQ: "French Southern Territories",
  AU: "Australia",
  MM: "Myanmar",
  BN: "Brunei",
  FM: "Micronesia",
  PW: "Palau",
  NZ: "New Zealand",
  KH: "Cambodia",
  CX: "Christmas Island",
  CK: "Cook Islands",
  FJ: "Fiji",
  CC: "Cocos Islands",
  ID: "Indonesia",
  KI: "Kiribati",
  LA: "Laos",
  MY: "Malaysia",
  MP: "Northern Mariana Islands",
  MH: "Marshall Islands",
  NC: "New Caledonia",
  NU: "Niue",
  NR: "Nauru",
  PF: "French Polynesia",
  PH: "Philippines",
  TL: "Timor-Leste",
  PG: "Papua New Guinea",
  PN: "Pitcairn Islands",
  SB: "Solomon Islands",
  AS: "American Samoa",
  WS: "Samoa",
  SG: "Singapore",
  TH: "Thailand",
  TO: "Tonga",
  TV: "Tuvalu",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  ZA: "South Africa",
  AO: "Angola",
  DZ: "Algeria",
  TF: "French Southern Territories",
  SH: "Saint Helena",
  BI: "Burundi",
  BJ: "Benin",
  BW: "Botswana",
  CF: "Central African Republic",
  CM: "Cameroon",
  CG: "Congo",
  KM: "Comoros",
  CV: "Cabo Verde",
  CI: "Côte d'Ivoire",
  DJ: "Djibouti",
  EG: "Egypt",
  ET: "Ethiopia",
  ER: "Eritrea",
  GA: "Gabon",
  GH: "Ghana",
  GM: "Gambia",
  GW: "Guinea-Bissau",
  GQ: "Equatorial Guinea",
  GN: "Guinea",
  BF: "Burkina Faso",
  KE: "Kenya",
  LR: "Liberia",
  SS: "South Sudan",
  LY: "Libya",
  LS: "Lesotho",
  MU: "Mauritius",
  MG: "Madagascar",
  ML: "Mali",
  MZ: "Mozambique",
  MR: "Mauritania",
  MW: "Malawi",
  NE: "Niger",
  NG: "Nigeria",
  NA: "Namibia",
  RE: "Réunion",
  RW: "Rwanda",
  SD: "Sudan",
  SN: "Senegal",
  SC: "Seychelles",
  SO: "Somalia",
  SL: "Sierra Leone",
  ST: "São Tomé and Príncipe",
  SZ: "Eswatini",
  TD: "Chad",
  TG: "Togo",
  TN: "Tunisia",
  TZ: "Tanzania",
  UG: "Uganda",
  CD: "Democratic Republic of the Congo",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  AR: "Argentina",
  BR: "Brazil",
  BO: "Bolivia",
  CL: "Chile",
  CO: "Colombia",
  EC: "Ecuador",
  FK: "Falkland Islands",
  GF: "French Guiana",
  GY: "Guyana",
  PY: "Paraguay",
  PE: "Peru",
  SR: "Suriname",
  UY: "Uruguay",
  VE: "Venezuela",
};